import os
import signal
import shutil
import shlex
import subprocess
import time
import textwrap
from typing import Optional, Tuple
import glob
import hashlib
from configs.path import CODEFLAWS_SOURCE_DIR, DEFECTS4C_OUT_DIR, DEFECTS4C_PATCHES_DIR
from core.utils import get_codeflaws_buggy_cfile
from data_loaders.defects4c_loader import (
    get_defects4c_raw_record,
    get_defects4c_source_path,
    parse_defects4c_bug_id,
)

TCPDUMP_RUN_ONE_TEST_SH = textwrap.dedent(r"""
    #!/usr/bin/env bash
    # Auto-generated by Unified-Debugging validation.
    # Run exactly one tcpdump test from tests/TESTLIST.

    set -uo pipefail
    HERE=$(cd "$(dirname "$0")" && pwd)
    TEST_ID="${1:?Usage: $0 <test_id>}"

    cd "$HERE/tests" || exit 2
    LINE=$(grep -E "^[[:space:]]*${TEST_ID}[[:space:]]" TESTLIST | head -n 1)
    if [[ -z "$LINE" ]]; then
      echo "[run_one_test] test_id '$TEST_ID' not in TESTLIST" >&2
      exit 3
    fi

    FIELDS=($LINE)
    NAME=${FIELDS[0]}
    INP=${FIELDS[1]}
    OUTP=${FIELDS[2]}
    OPTS="${FIELDS[@]:3}"

    OUTPUT=$(./TESTonce "$NAME" "$INP" "$OUTP" "$OPTS" 2>&1)
    STATUS=$?
    echo "$OUTPUT"
    if [[ $STATUS -ne 0 ]] || grep -q "TEST FAILED" <<<"$OUTPUT"; then
      exit 1
    fi
    exit 0
""").lstrip()

class SandboxAdapter:
    """Class Cầu nối cơ sở để chuẩn hoá mọi dataset (Codeflaws, Defects4C, Defects4J)"""
    def __init__(self, bug_id):
        self.bug_id = bug_id
        self.last_validation_details = {}

    def get_source_path(self):
        """Trả về đường dẫn tuyệt đối đến file mã nguồn đang chứa lỗi"""
        raise NotImplementedError("Phải trả về đường dẫn tuyệt đối đến file mã nguồn cần sửa")

    def validate(self, patched_file_path, src_basename=None, src_relpath=None):
        """
        Nhận vào đường dẫn file tạm đã được vá:
        1. Backup file gốc.
        2. Dán đè file vá rồi biên dịch / chạy test.
        3. Phục hồi file gốc và xóa rác.

        Args:
            patched_file_path: Đường dẫn file đã được vá (host).
            src_basename:      Basename của file mã nguồn mà patch này nhằm
                               thay thế (vd: ``print-isakmp.c``). Cần thiết
                               khi FL chỉ ra lỗi ở một file phụ thay vì file
                               chính. Nếu None, adapter dùng file chính.

        Trả về tuple: (is_valid: bool, passed_tests: list, failed_tests: list)
        """
        raise NotImplementedError("Phải trả về (is_valid, post_passed_tests, post_failed_tests)")

class CodeflawsAdapter(SandboxAdapter):
    """
    Adapter xử lý thư mục và kịch bản đặc thù của Codeflaws.

    Thay vì gọi test-genprog.sh (phụ thuộc GNU time/diff, không chạy trên macOS),
    adapter tự compile bằng Makefile, chạy chương trình, và so sánh output bằng Python.
    """
    def get_source_path(self):
        bug_dir   = os.path.join(CODEFLAWS_SOURCE_DIR, self.bug_id)
        cfilename = get_codeflaws_buggy_cfile(self.bug_id)
        return os.path.join(bug_dir, cfilename)

    def _parse_test_cases(self, bug_dir):
        """
        Phát hiện tất cả test cases có sẵn trong thư mục bug dựa trên file input-*/output-*.
        Trả về list of (test_id, input_file, expected_output_file).
        """
        test_cases = []
        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-pos*"))):
            basename = os.path.basename(inp)
            num = basename.replace("input-pos", "")
            out = os.path.join(bug_dir, f"output-pos{num}")
            if os.path.exists(out):
                test_cases.append((f"pos{num}", inp, out))

        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-neg*"))):
            basename = os.path.basename(inp)
            num = basename.replace("input-neg", "")
            out = os.path.join(bug_dir, f"output-neg{num}")
            if os.path.exists(out):
                test_cases.append((f"neg{num}", inp, out))

        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-heldout-pos*"))):
            basename = os.path.basename(inp)
            tag = basename.replace("input-", "")
            out = os.path.join(bug_dir, f"output-{tag}")
            if os.path.exists(out):
                test_cases.append((tag, inp, out))

        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-heldout-neg*"))):
            basename = os.path.basename(inp)
            tag = basename.replace("input-", "")
            out = os.path.join(bug_dir, f"output-{tag}")
            if os.path.exists(out):
                test_cases.append((tag, inp, out))

        return test_cases

    def validate(self, patched_file_path, src_basename=None, src_relpath=None):
        self.last_validation_details = {}
        # Codeflaws chỉ có 1 file .c cho mỗi bug → bỏ qua src_basename.
        bug_dir = os.path.join(CODEFLAWS_SOURCE_DIR, self.bug_id)
        original_file = self.get_source_path()
        expected_name = os.path.basename(original_file)
        exe_name = expected_name.replace(".c", "")
        backup_file = os.path.join(bug_dir, f"{expected_name}.bak")

        if not os.path.exists(original_file):
            return self._validation_error_result("source_file_missing")

        is_valid = False
        failed_tests = []
        passed_tests = []
        try:
            shutil.copy2(original_file, backup_file)
            patched_file_path = os.path.abspath(patched_file_path)
            if patched_file_path != os.path.abspath(original_file):
                shutil.copy2(patched_file_path, original_file)

            compile_ok = self._compile(bug_dir, expected_name, exe_name)
            if not compile_ok:
                print(f"    [Sandbox] Compilation failed cho {self.bug_id}.")
                return self._validation_error_result("compile_failed")

            exe_path = os.path.join(bug_dir, exe_name)
            test_cases = self._parse_test_cases(bug_dir)

            if not test_cases:
                return self._validation_error_result("no_test_cases_found")

            for tc_id, input_file, expected_output_file in test_cases:
                passed = self._run_one_test(exe_path, input_file, expected_output_file)
                if passed:
                    passed_tests.append(tc_id)
                else:
                    failed_tests.append(tc_id)

            if not failed_tests and len(passed_tests) > 0:
                is_valid = True

        finally:
            if os.path.exists(backup_file):
                shutil.move(backup_file, original_file)
            exe_file = os.path.join(bug_dir, exe_name)
            obj_file = os.path.join(bug_dir, f"{exe_name}.o")
            for f in [exe_file, obj_file]:
                if os.path.exists(f):
                    os.remove(f)

        self.last_validation_details = {
            "validation_error": "",
            "full_post_passed_tests": list(passed_tests),
            "full_post_failed_tests": list(failed_tests),
        }
        return is_valid, passed_tests, failed_tests

    def _validation_error_result(self, reason: str):
        self.last_validation_details = {
            "validation_error": reason,
            "full_post_passed_tests": [],
            "full_post_failed_tests": [],
        }
        return False, [], []

    def _compile(self, bug_dir, source_name, exe_name):
        """Compile sử dụng Makefile, fallback sang gcc trực tiếp."""
        makefile = os.path.join(bug_dir, "Makefile")

        if os.path.exists(makefile):
            result = subprocess.run(
                ["make", f"FILENAME={exe_name}"],
                cwd=bug_dir,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                timeout=30
            )
            if result.returncode == 0:
                return True

        result = subprocess.run(
            [
                "gcc",
                "-fno-optimize-sibling-calls", "-fno-strict-aliasing",
                "-fno-asm", "-std=c99",
                "-Wno-error=implicit-function-declaration",
                "-O0",
                source_name, "-o", exe_name, "-lm"
            ],
            cwd=bug_dir,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            timeout=30
        )
        return result.returncode == 0

    def _run_one_test(self, exe_path, input_file, expected_output_file, timeout=10):
        """
        Chạy exe với input, so sánh stdout với expected output.
        So sánh ignore trailing whitespace mỗi dòng (tương đương diff --ignore-trailing-space).

        Dùng stdin=PIPE + communicate(input=data) để Python quản lý cả stdin/stdout
        qua pipe — timeout mới hoạt động đúng trên mọi nền tảng (kể cả macOS Python 3.9).
        Dùng start_new_session=True + os.killpg(SIGKILL) để kill toàn process group.
        """
        try:
            with open(input_file, "r") as f:
                input_data = f.read()
            with open(expected_output_file, "r") as f:
                expected = f.read()
        except Exception:
            return False

        try:
            proc = subprocess.Popen(
                [exe_path],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                start_new_session=True,  # proc.pid == pgid khi dùng start_new_session
            )
            try:
                stdout, _ = proc.communicate(input=input_data, timeout=timeout)
            except subprocess.TimeoutExpired:
                # SIGKILL toàn bộ process group
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except (ProcessLookupError, PermissionError):
                    proc.kill()
                # Drain pipes với timeout ngắn để tránh block vô hạn
                try:
                    proc.communicate(timeout=2)
                except subprocess.TimeoutExpired:
                    pass
                return False
        except Exception:
            try:
                proc.kill()
                proc.wait()
            except Exception:
                pass
            return False

        return _compare_output(stdout or "", expected)


class Defects4CAdapter(SandboxAdapter):
    """Adapter validate patch Defects4C qua Docker/local service đã warmup."""

    def __init__(self, bug_id, data_folder: Optional[str] = None):
        super().__init__(bug_id)
        self.data_folder = data_folder

    def get_source_path(self):
        return get_defects4c_source_path(self.bug_id, data_folder=self.data_folder)

    def validate(self, patched_file_path, src_basename=None, src_relpath=None):
        self.last_validation_details = {}
        raw = get_defects4c_raw_record(self.bug_id, data_folder=self.data_folder)
        if not raw:
            return self._validation_error_result("metadata_not_found")

        bug_meta = raw.get("raw", raw)
        if not src_relpath and not src_basename:
            return self._validation_error_result("missing_src_target")

        project = bug_meta.get("project") or parse_defects4c_bug_id(self.bug_id)[0]
        sha = bug_meta.get("commit_after") or parse_defects4c_bug_id(self.bug_id)[1]
        commit_before = bug_meta.get("commit_before")
        if not commit_before:
            return self._validation_error_result("missing_commit_before")
        if not sha:
            return self._validation_error_result("missing_commit_after")

        test_ids = self._collect_defects4c_test_ids(project, sha, bug_meta)
        try:
            with open(patched_file_path, "rb") as f:
                content = f.read()
        except Exception:
            return self._validation_error_result("patch_read_error")

        # Giữ artifact patch như luồng cũ để tiện trace/debug.
        md5 = hashlib.md5(content).hexdigest()
        host_patch_dir = os.path.join(DEFECTS4C_PATCHES_DIR, project, "unified_debugging")
        os.makedirs(host_patch_dir, exist_ok=True)
        patch_label = (src_relpath or src_basename or "unknown").replace("/", "__")
        host_patch_path = os.path.join(host_patch_dir, f"{md5}@{sha}___{patch_label}")
        with open(host_patch_path, "wb") as f:
            f.write(content)

        return self._validate_metadata_patch(
            patched_file_path=patched_file_path,
            src_basename=src_basename,
            src_relpath=src_relpath,
            bug_meta=bug_meta,
            project=project,
            commit_after=sha,
            commit_before=commit_before,
            test_ids=test_ids,
        )

    def _validate_metadata_patch(
        self,
        patched_file_path: str,
        src_basename: str,
        src_relpath: Optional[str],
        bug_meta: dict,
        project: str,
        commit_after: str,
        commit_before: str,
        test_ids: list,
    ):
        host_repo = bug_meta.get("source_repo_dir") or ""
        container_repo = bug_meta.get("container_repo_dir") or ""
        if not host_repo or not os.path.isdir(host_repo):
            return self._validation_error_result("repo_not_found")
        if not container_repo:
            return self._validation_error_result("container_repo_not_found")

        container = self._select_defects4c_container(bug_meta)
        if not container:
            return self._validation_error_result("container_not_running")

        src_files = self._phase_a_src_files(bug_meta)
        if not self._prepare_generic_workspace(
            container=container,
            container_repo=container_repo,
            commit_after=commit_after,
            commit_before=commit_before,
            src_files=src_files,
            clean=True,
        ):
            return self._validation_error_result("phase_a_prepare_failed")

        target_relpath = self._resolve_source_relpath(
            bug_meta=bug_meta,
            src_basename=src_basename,
            src_relpath=src_relpath,
            src_files=src_files,
        )
        if not target_relpath:
            self._reset_generic_workspace(container, container_repo)
            return self._validation_error_result(f"source_not_found:{src_relpath or src_basename}")

        if not self._apply_generic_patch(container, patched_file_path, container_repo, target_relpath):
            self._reset_generic_workspace(container, container_repo)
            return self._validation_error_result(f"patch_copy_failed:{target_relpath}")

        suite_ok, full_passed, full_failed, validation_error = self._run_metadata_test_suite(
            container=container,
            container_repo=container_repo,
            bug_meta=bug_meta,
            test_ids=test_ids,
        )
        self._reset_generic_workspace(container, container_repo)

        if validation_error:
            self.last_validation_details = {
                "validation_error": validation_error,
                "full_post_passed_tests": [],
                "full_post_failed_tests": [],
                "phase_a_suite_ok": False,
                "phase_a_base_commit": commit_after,
                "phase_a_buggy_overlay_commit": commit_before,
                "phase_a_buggy_overlay_files": list(src_files),
            }
            return False, [], []

        if (not suite_ok) and (not full_failed) and (not full_passed):
            self.last_validation_details = {
                "validation_error": "metadata_suite_failed",
                "full_post_passed_tests": [],
                "full_post_failed_tests": [],
                "phase_a_suite_ok": False,
                "phase_a_base_commit": commit_after,
                "phase_a_buggy_overlay_commit": commit_before,
                "phase_a_buggy_overlay_files": list(src_files),
            }
            return False, [], []

        full_failed_set = set(full_failed)
        full_passed = full_passed or [t for t in test_ids if t not in full_failed_set]
        fixed_fail_excluded = self._fixed_fail_excluded_tests(bug_meta)
        effective_failed = [t for t in full_failed if t not in fixed_fail_excluded]
        effective_passed = [t for t in full_passed if t not in fixed_fail_excluded]

        self.last_validation_details = {
            "validation_error": "",
            "full_post_passed_tests": list(full_passed),
            "full_post_failed_tests": list(full_failed),
            "effective_post_passed_tests": list(effective_passed),
            "effective_post_failed_tests": list(effective_failed),
            "patch_comparison_post_passed_tests": list(effective_passed),
            "patch_comparison_post_failed_tests": list(effective_failed),
            "fixed_fail_excluded_tests": sorted(fixed_fail_excluded),
            "phase_a_suite_ok": suite_ok,
            "phase_a_base_commit": commit_after,
            "phase_a_buggy_overlay_commit": commit_before,
            "phase_a_buggy_overlay_files": list(src_files),
        }
        print(
            f"    [Defects4C:{bug_meta.get('data_folder', 'metadata')}] full_scope_tests={len(test_ids)} "
            f"full_failed_total={len(full_failed)} effective_failed_total={len(effective_failed)}"
        )
        if not effective_failed:
            return True, list(effective_passed), []
        return False, list(effective_passed), list(effective_failed)

    def _validation_error_result(self, reason: str):
        self.last_validation_details = {
            "validation_error": reason,
            "full_post_passed_tests": [],
            "full_post_failed_tests": [],
        }
        return False, [], []

    def _fixed_fail_excluded_tests(self, bug_meta: dict) -> set:
        tests = bug_meta.get("tests", []) if isinstance(bug_meta, dict) else []
        excluded = set()
        for test in tests:
            if not isinstance(test, dict):
                continue
            tid = str(test.get("test_id") or "").strip()
            if not tid:
                continue
            outcome = str(test.get("outcome") or "").upper()
            outcome_fixed = str(test.get("outcome_fixed") or "").upper()
            if outcome in ("FAIL", "FAILED") and outcome_fixed in ("FAIL", "FAILED"):
                excluded.add(tid)
        return excluded

    def _resolve_source_relpath(
        self,
        bug_meta: dict,
        src_basename: Optional[str],
        src_relpath: Optional[str],
        src_files: Optional[list] = None,
    ) -> Optional[str]:
        buggy_tree_dir = bug_meta.get("buggy_tree_dir") or ""
        if src_relpath:
            rel = src_relpath.strip().replace("\\", "/")
            if rel and not rel.startswith("/") and ".." not in rel.split("/"):
                buggy_path = os.path.join(buggy_tree_dir, rel) if buggy_tree_dir else ""
                if not buggy_tree_dir or os.path.isfile(buggy_path):
                    return rel
            return None

        if not src_basename:
            return None
        for rel in src_files or []:
            if os.path.basename(rel) != src_basename:
                continue
            exact = os.path.join(buggy_tree_dir, rel) if buggy_tree_dir else ""
            if os.path.isfile(exact):
                return rel

        return None

    def _select_defects4c_container(self, bug_meta: Optional[dict] = None) -> str:
        bug_meta = bug_meta or {}
        env_c = (os.getenv("DEFECTS4C_CONTAINER") or "").strip()
        folder = str(bug_meta.get("data_folder") or bug_meta.get("metadata_slug") or "").strip()
        project = str(bug_meta.get("project") or "").strip()
        project_tail = project.split("___")[-1].lower() if project else ""
        candidates = []
        if env_c:
            candidates.append(env_c)
        if folder:
            candidates.append(f"my_defects4c_{folder.lower()}")
        if project_tail and project_tail != folder.lower():
            candidates.append(f"my_defects4c_{project_tail}")
        candidates.append("my_defects4c")
        for name in dict.fromkeys(candidates):
            if shutil.which("docker") and self._docker_container_running(name):
                return name
        return ""

    def _phase_a_src_files(self, bug_meta: dict) -> list:
        values = bug_meta.get("src_files")
        if not isinstance(values, list) or not values:
            files = bug_meta.get("files", {})
            if isinstance(files, dict):
                values = files.get("src", [])
        if not isinstance(values, list) or not values:
            rel = bug_meta.get("source_relpath")
            values = [rel] if rel else []

        out = []
        for value in values:
            if not isinstance(value, str):
                continue
            cleaned = value.strip().replace("\\", "/")
            if cleaned and not cleaned.startswith("/") and ".." not in cleaned.split("/"):
                out.append(cleaned)
        return list(dict.fromkeys(out))

    def _prepare_generic_workspace(
        self,
        container: str,
        container_repo: str,
        commit_after: str,
        commit_before: str,
        src_files: list,
        clean: bool,
    ) -> bool:
        clean_cmd = "git -C \"$repo\" clean -ffdx && " if clean else ""
        overlay_cmd = ""
        if src_files:
            src_args = " ".join(shlex.quote(path) for path in src_files)
            overlay_cmd = f" && git -C \"$repo\" checkout --force \"$before\" -- {src_args}"
        restore_test_helper_cmd = self._restore_known_test_helpers_cmd()
        cmd = (
            f"repo={shlex.quote(container_repo)}; "
            f"after={shlex.quote(commit_after)}; "
            f"before={shlex.quote(commit_before)}; "
            "if [ ! -d \"$repo/.git\" ]; then exit 2; fi; "
            "git -C \"$repo\" reset --hard && "
            f"{clean_cmd}"
            "git -C \"$repo\" checkout -f \"$after\""
            f"{overlay_cmd} && "
            f"{restore_test_helper_cmd}"
        )
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return result.returncode == 0

    def _restore_known_test_helpers_cmd(self) -> str:
        tcpdump_runner = shlex.quote(TCPDUMP_RUN_ONE_TEST_SH)
        return (
            "if [ -f \"$repo/tests/TESTLIST\" ] && [ -x \"$repo/tests/TESTonce\" ] "
            "&& [ ! -f \"$repo/run_one_test.sh\" ]; then "
            f"printf %s {tcpdump_runner} > \"$repo/run_one_test.sh\" && "
            "chmod +x \"$repo/run_one_test.sh\"; "
            "fi"
        )

    def _reset_generic_workspace(self, container: str, container_repo: str) -> bool:
        cmd = (
            f"repo={shlex.quote(container_repo)}; "
            "if [ -d \"$repo/.git\" ]; then "
            "git -C \"$repo\" reset --hard >/dev/null 2>&1; "
            "fi"
        )
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return result.returncode == 0

    def _apply_generic_patch(
        self,
        container: str,
        patched_file_path: str,
        container_repo: str,
        relpath: str,
    ) -> bool:
        rel = (relpath or "").strip().replace("\\", "/")
        if not rel or rel.startswith("/") or ".." in rel.split("/"):
            return False

        container_target = f"{container_repo.rstrip('/')}/{rel}"
        tmp_in_container = f"/tmp/apr_patch_{int(time.time() * 1000)}_{os.getpid()}.c"
        cp_in = subprocess.run(
            ["docker", "cp", patched_file_path, f"{container}:{tmp_in_container}"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if cp_in.returncode != 0:
            return False
        install_cmd = (
            f"dst={shlex.quote(container_target)}; "
            f"tmp={shlex.quote(tmp_in_container)}; "
            "mkdir -p \"$(dirname \"$dst\")\" && cp \"$tmp\" \"$dst\" && rm -f \"$tmp\""
        )
        cp_out = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", install_cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return cp_out.returncode == 0

    def _run_metadata_test_suite(
        self,
        container: str,
        container_repo: str,
        bug_meta: dict,
        test_ids: list,
    ) -> Tuple[bool, list, list, str]:
        compile_cmd = (bug_meta.get("compile_cmd") or "").strip()
        template = (bug_meta.get("test_cmd_template") or "").strip()
        if not compile_cmd or not template or not test_ids:
            return False, [], [], "metadata_suite_config_missing"

        helper_path = self._extract_metadata_helper_path(template)
        lines = [
            "set +e",
            f"cd {shlex.quote(container_repo)} || exit 2",
        ]
        if helper_path:
            lines.extend([
                f"if [ ! -f {shlex.quote(helper_path)} ]; then",
                f"  echo __UD_TEST_HELPER_MISSING__ {shlex.quote(helper_path)}",
                "  exit 98",
                "fi",
            ])
        lines.extend([
            f"({compile_cmd}) >/tmp/udbg_compile.log 2>&1",
            "compile_rc=$?",
            "if [ $compile_rc -ne 0 ]; then echo __UD_COMPILE_FAIL__; tail -80 /tmp/udbg_compile.log; exit 97; fi",
        ])
        for tid in test_ids:
            test_cmd = template.replace("{test_id}", shlex.quote(tid))
            marker = shlex.quote(tid)
            lines.extend([
                f"({test_cmd}) >/tmp/udbg_test.log 2>&1",
                "rc=$?",
                f"if [ $rc -eq 0 ]; then echo __UD_PASS__ {marker}; else echo __UD_FAIL__ {marker}; fi",
            ])
        script = "\n".join(lines)
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", script],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60 * 40,
        )
        passed, failed = [], []
        for line in (result.stdout or "").splitlines():
            if line.startswith("__UD_PASS__ "):
                passed.append(line.split(" ", 1)[1].strip())
            elif line.startswith("__UD_FAIL__ "):
                failed.append(line.split(" ", 1)[1].strip())
            elif line.startswith("__UD_TEST_HELPER_MISSING__ "):
                missing = line.split(" ", 1)[1].strip()
                return False, [], [], f"test_helper_missing:{missing}"
        if result.returncode == 97:
            return False, [], [], "compile_failed"
        if result.returncode == 98:
            return False, [], [], "test_helper_missing"
        if result.returncode != 0 and not failed and not passed:
            return False, [], [], "metadata_suite_failed"
        return not failed, passed, failed, ""

    def _extract_metadata_helper_path(self, template: str) -> Optional[str]:
        try:
            parts = shlex.split(template)
        except ValueError:
            return None
        for part in parts:
            if part.endswith(".sh") and "{test_id}" not in part:
                return part
        return None

    def _collect_defects4c_test_ids(self, project: str, sha: str, bug_meta: Optional[dict] = None) -> list:
        metadata_ids = self._metadata_test_ids_from_bug_meta(bug_meta or {})
        if metadata_ids:
            return metadata_ids

        host_repo = (bug_meta or {}).get("source_repo_dir") or os.path.join(
            DEFECTS4C_OUT_DIR,
            project,
            f"git_repo_dir_{sha}",
        )
        host_testlist = os.path.join(
            host_repo,
            "tests",
            "TESTLIST",
        )
        if not os.path.isfile(host_testlist):
            return []
        ids = []
        try:
            with open(host_testlist, "r", errors="ignore") as f:
                for line in f:
                    s = line.strip()
                    if not s or s.startswith("#"):
                        continue
                    parts = s.split()
                    if parts:
                        ids.append(parts[0])
        except Exception:
            return []
        return ids

    def _metadata_test_ids_from_bug_meta(self, bug_meta: dict) -> list:
        tests = bug_meta.get("tests", []) if isinstance(bug_meta, dict) else []
        out = []
        for test in tests:
            if not isinstance(test, dict):
                continue
            tid = str(test.get("test_id", "")).strip()
            if tid:
                out.append(tid)
        return self._unique_test_ids(out)

    @staticmethod
    def _unique_test_ids(values) -> list:
        seen = set()
        out = []
        for value in values:
            if value in seen:
                continue
            seen.add(value)
            out.append(value)
        return out

    def _docker_container_running(self, container):
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Running}}", container],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return result.returncode == 0 and result.stdout.decode().strip() == "true"


def _compare_output(actual: str, expected: str) -> bool:
    """
    So sánh output giống diff --brief --ignore-trailing-space:
    bỏ qua trailing whitespace mỗi dòng, bỏ qua trailing newlines cuối file.
    """
    actual_lines = [line.rstrip() for line in actual.splitlines()]
    expected_lines = [line.rstrip() for line in expected.splitlines()]

    while actual_lines and actual_lines[-1] == "":
        actual_lines.pop()
    while expected_lines and expected_lines[-1] == "":
        expected_lines.pop()

    return actual_lines == expected_lines


def defects4c_docker_ready(dataset_name: str = "defects4c") -> Tuple[bool, str]:
    """
    Kiểm tra APR/validate Defects4C có thể chạy không (Docker + container đang Running).

    Returns:
        (True, container_name) nếu tìm được container phù hợp.
        (False, message) nếu thiếu Docker hoặc không có container nào đang chạy.
    """
    if not shutil.which("docker"):
        return False, "Docker không có trong PATH — validate patch Defects4C cần Docker."

    candidates = []
    env_c = (os.getenv("DEFECTS4C_CONTAINER") or "").strip()
    if env_c:
        candidates.append(env_c)
    ds = (dataset_name or "").strip().lower()
    if ds.startswith("defects4c-"):
        ds = ds[len("defects4c-"):]
    ordered = []
    if ds and ds != "defects4c":
        ordered.append(f"my_defects4c_{ds}")
    ordered.append("my_defects4c")
    for name in ordered:
        if name not in candidates:
            candidates.append(name)

    for name in candidates:
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Running}}", name],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
        if result.returncode == 0 and result.stdout.decode().strip() == "true":
            return True, name

    tried = ", ".join(candidates)
    hint = env_c or (f"my_defects4c_{ds}" if ds and ds != "defects4c" else "my_defects4c")
    return (
        False,
        f"Không có container Defects4C đang chạy (đã thử: {tried}). "
        f"Khởi container rồi chạy lại, hoặc đặt DEFECTS4C_CONTAINER và docker start <tên>. "
        f"Ví dụ: docker start {hint}",
    )


def get_sandbox_adapter(dataset_name, bug_id):
    """Factory để cấp phát Adapter tùy theo dataset_name truyền vào"""
    ds_lc = dataset_name.strip().lower()
    if ds_lc == "codeflaws":
        return CodeflawsAdapter(bug_id)

    # Any non-Codeflaws dataset handled here is expected to be a Defects4C
    # data folder under out_tmp_dirs/unified_debugging/<dataset_name>/metadata.
    defects4c_folder = ds_lc
    if defects4c_folder.startswith("defects4c-"):
        defects4c_folder = defects4c_folder[len("defects4c-"):]
    if ds_lc == "defects4c":
        return Defects4CAdapter(bug_id)
    try:
        if get_defects4c_raw_record(bug_id, data_folder=defects4c_folder):
            return Defects4CAdapter(bug_id, data_folder=defects4c_folder)
    except ValueError:
        pass

    raise ValueError(f"Dataset '{dataset_name}' chưa có Adapter tương ứng hỗ trợ!")
