import os
import signal
import shutil
import shlex
import subprocess
import time
import textwrap
import ast
from typing import Optional, Tuple
import glob
import hashlib
from configs.path import CODEFLAWS_SOURCE_DIR, DEFECTS4C_OUT_DIR, DEFECTS4C_PATCHES_DIR, DEFECTS4C_TPL_DIR
from core.apr.compilation_database import (
    find_build_compilation_database,
    materialize_analysis_database,
    write_single_file_database,
)
from core.test_filtering import is_zero_test_noop_pass_test
from core.utils import get_codeflaws_buggy_cfile
from data_loaders.defects4c_loader import (
    get_defects4c_raw_record,
    get_defects4c_source_path,
    parse_defects4c_bug_id,
)

TCPDUMP_RUN_ONE_TEST_SH = textwrap.dedent(r"""
    #!/usr/bin/env bash
    # Auto-generated by Unified-Debugging validation.
    # Run exactly one tcpdump test from tests/TESTLIST.

    set -uo pipefail
    HERE=$(cd "$(dirname "$0")" && pwd)
    TEST_ID="${1:?Usage: $0 <test_id>}"

    cd "$HERE/tests" || exit 2
    LINE=$(grep -E "^[[:space:]]*${TEST_ID}[[:space:]]" TESTLIST | head -n 1)
    if [[ -z "$LINE" ]]; then
      echo "[run_one_test] test_id '$TEST_ID' not in TESTLIST" >&2
      exit 3
    fi

    FIELDS=($LINE)
    NAME=${FIELDS[0]}
    INP=${FIELDS[1]}
    OUTP=${FIELDS[2]}
    OPTS="${FIELDS[@]:3}"

    OUTPUT=$(./TESTonce "$NAME" "$INP" "$OUTP" "$OPTS" 2>&1)
    STATUS=$?
    echo "$OUTPUT"
    if [[ $STATUS -ne 0 ]] || grep -q "TEST FAILED" <<<"$OUTPUT"; then
      exit 1
    fi
    exit 0
""").lstrip()

LIBYANG_CMOCKA_FILTER_PATCH_SCRIPT = r"""
import sys
from pathlib import Path

repo = Path(sys.argv[1])
marker = "BUILD_META_CMOCKA_TEST_FILTER"
call = "return cmocka_run_group_tests("
hook = (
    "{\n"
    "        const char *build_meta_filter = getenv(\"BUILD_META_CMOCKA_TEST_FILTER\");\n"
    "        if (build_meta_filter && build_meta_filter[0]) {\n"
    "            cmocka_set_test_filter(build_meta_filter);\n"
    "        }\n"
    "    }\n"
    "    return cmocka_run_group_tests("
)

candidates = []
patched = 0
for path in sorted((repo / "tests").rglob("*.c")):
    text = path.read_text(encoding="utf-8", errors="replace")
    if call not in text:
        continue
    candidates.append(path)
    if marker in text:
        continue
    if "#include <stdlib.h>" not in text:
        if "#include <cmocka.h>" in text:
            text = text.replace(
                "#include <cmocka.h>",
                "#include <cmocka.h>\n#include <stdlib.h>",
                1,
            )
    new_text = text.replace(call, hook, 1)
    if new_text == text:
        continue
    path.write_text(new_text, encoding="utf-8")
    patched += 1

unpatched = [str(path.relative_to(repo)) for path in candidates if marker not in path.read_text(
    encoding="utf-8", errors="replace"
)]
if not candidates:
    print("no CMocka test entrypoints found", file=sys.stderr)
    raise SystemExit(2)
if unpatched:
    print("unpatched CMocka test entrypoints: " + ", ".join(unpatched), file=sys.stderr)
    raise SystemExit(3)

print(f"libyang_cmocka_filter_sources:{len(candidates)}")
print(f"libyang_cmocka_filter_patched:{patched}")
""".lstrip()

class SandboxAdapter:
    """Class Cầu nối cơ sở để chuẩn hoá mọi dataset (Codeflaws, Defects4C, Defects4J)"""
    def __init__(self, bug_id):
        self.bug_id = bug_id
        self.last_validation_details = {}

    def get_source_path(self):
        """Trả về đường dẫn tuyệt đối đến file mã nguồn đang chứa lỗi"""
        raise NotImplementedError("Phải trả về đường dẫn tuyệt đối đến file mã nguồn cần sửa")

    def prepare_compilation_database(
        self, *, source_root: str, source_path: str, src_relpath: Optional[str] = None
    ) -> dict:
        """Expose an existing build database without inventing compiler flags."""
        del source_path, src_relpath
        database = find_build_compilation_database([source_root])
        if not database:
            return {
                "version": 1,
                "available": False,
                "database_path": "",
                "provider": "sandbox_existing_database",
                "diagnostics": ["sandbox_compilation_database_missing"],
            }
        root = os.path.realpath(source_root)
        return {
            "version": 1,
            "available": True,
            "database_path": database,
            "source_database": database,
            "build_source_root": root,
            "analysis_source_root": root,
            "allowed_source_roots": [root],
            "provider": "sandbox_existing_database",
            "diagnostics": [],
        }

    def validate(self, patched_file_path, src_basename=None, src_relpath=None,
                 exclude_fixed_fail_tests=True):
        """
        Nhận vào đường dẫn file tạm đã được vá:
        1. Backup file gốc.
        2. Dán đè file vá rồi biên dịch / chạy test.
        3. Phục hồi file gốc và xóa rác.

        Args:
            patched_file_path: Đường dẫn file đã được vá (host).
            src_basename:      Basename của file mã nguồn mà patch này nhằm
                               thay thế (vd: ``print-isakmp.c``). Cần thiết
                               khi FL chỉ ra lỗi ở một file phụ thay vì file
                               chính. Nếu None, adapter dùng file chính.

        Trả về tuple: (is_valid: bool, passed_tests: list, failed_tests: list)
        """
        raise NotImplementedError("Phải trả về (is_valid, post_passed_tests, post_failed_tests)")

class CodeflawsAdapter(SandboxAdapter):
    """
    Adapter xử lý thư mục và kịch bản đặc thù của Codeflaws.

    Thay vì gọi test-genprog.sh (phụ thuộc GNU time/diff, không chạy trên macOS),
    adapter tự compile bằng Makefile, chạy chương trình, và so sánh output bằng Python.
    """
    def get_source_path(self):
        bug_dir   = os.path.join(CODEFLAWS_SOURCE_DIR, self.bug_id)
        cfilename = get_codeflaws_buggy_cfile(self.bug_id)
        return os.path.join(bug_dir, cfilename)

    def prepare_compilation_database(
        self, *, source_root: str, source_path: str, src_relpath: Optional[str] = None
    ) -> dict:
        del src_relpath
        bug_dir = os.path.realpath(source_root)
        source = os.path.realpath(source_path)
        if not os.path.isfile(source):
            return {
                "version": 1,
                "available": False,
                "database_path": "",
                "provider": "codeflaws_validation_command",
                "diagnostics": ["codeflaws_compilation_source_missing"],
            }
        output = os.path.join(bug_dir, ".apr", "compile_commands.json")
        return write_single_file_database(
            output_database=output,
            directory=bug_dir,
            source_path=source,
            arguments=[
                "gcc", "-fno-optimize-sibling-calls", "-fno-strict-aliasing",
                "-fno-asm", "-std=c99", "-Wno-error=implicit-function-declaration",
                "-O0", source, "-o", os.path.join(bug_dir, ".apr", "analysis.out"),
                "-lm",
            ],
            provider="codeflaws_validation_fallback_command",
        )

    def _parse_test_cases(self, bug_dir):
        """
        Phát hiện tất cả test cases có sẵn trong thư mục bug dựa trên file input-*/output-*.
        Trả về list of (test_id, input_file, expected_output_file).
        """
        test_cases = []
        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-pos*"))):
            basename = os.path.basename(inp)
            num = basename.replace("input-pos", "")
            out = os.path.join(bug_dir, f"output-pos{num}")
            if os.path.exists(out):
                test_cases.append((f"pos{num}", inp, out))

        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-neg*"))):
            basename = os.path.basename(inp)
            num = basename.replace("input-neg", "")
            out = os.path.join(bug_dir, f"output-neg{num}")
            if os.path.exists(out):
                test_cases.append((f"neg{num}", inp, out))

        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-heldout-pos*"))):
            basename = os.path.basename(inp)
            tag = basename.replace("input-", "")
            out = os.path.join(bug_dir, f"output-{tag}")
            if os.path.exists(out):
                test_cases.append((tag, inp, out))

        for inp in sorted(glob.glob(os.path.join(bug_dir, "input-heldout-neg*"))):
            basename = os.path.basename(inp)
            tag = basename.replace("input-", "")
            out = os.path.join(bug_dir, f"output-{tag}")
            if os.path.exists(out):
                test_cases.append((tag, inp, out))

        return test_cases

    def validate(self, patched_file_path, src_basename=None, src_relpath=None,
                 exclude_fixed_fail_tests=True):
        self.last_validation_details = {}
        # Codeflaws chỉ có 1 file .c cho mỗi bug → bỏ qua src_basename.
        bug_dir = os.path.join(CODEFLAWS_SOURCE_DIR, self.bug_id)
        original_file = self.get_source_path()
        expected_name = os.path.basename(original_file)
        exe_name = expected_name.replace(".c", "")
        backup_file = os.path.join(bug_dir, f"{expected_name}.bak")

        if not os.path.exists(original_file):
            return self._validation_error_result("source_file_missing")

        is_valid = False
        failed_tests = []
        passed_tests = []
        try:
            shutil.copy2(original_file, backup_file)
            patched_file_path = os.path.abspath(patched_file_path)
            if patched_file_path != os.path.abspath(original_file):
                shutil.copy2(patched_file_path, original_file)

            compile_ok = self._compile(bug_dir, expected_name, exe_name)
            if not compile_ok:
                print(f"    [Sandbox] Compilation failed cho {self.bug_id}.")
                return self._validation_error_result("compile_failed")

            exe_path = os.path.join(bug_dir, exe_name)
            test_cases = self._parse_test_cases(bug_dir)

            if not test_cases:
                return self._validation_error_result("no_test_cases_found")

            for tc_id, input_file, expected_output_file in test_cases:
                passed = self._run_one_test(exe_path, input_file, expected_output_file)
                if passed:
                    passed_tests.append(tc_id)
                else:
                    failed_tests.append(tc_id)

            if not failed_tests and len(passed_tests) > 0:
                is_valid = True

        finally:
            if os.path.exists(backup_file):
                shutil.move(backup_file, original_file)
            exe_file = os.path.join(bug_dir, exe_name)
            obj_file = os.path.join(bug_dir, f"{exe_name}.o")
            for f in [exe_file, obj_file]:
                if os.path.exists(f):
                    os.remove(f)

        self.last_validation_details = {
            "validation_error": "",
            "full_post_passed_tests": list(passed_tests),
            "full_post_failed_tests": list(failed_tests),
        }
        return is_valid, passed_tests, failed_tests

    def _validation_error_result(self, reason: str):
        self.last_validation_details = {
            "validation_error": reason,
            "full_post_passed_tests": [],
            "full_post_failed_tests": [],
        }
        return False, [], []

    def _compile(self, bug_dir, source_name, exe_name):
        """Compile sử dụng Makefile, fallback sang gcc trực tiếp."""
        makefile = os.path.join(bug_dir, "Makefile")

        if os.path.exists(makefile):
            result = subprocess.run(
                ["make", f"FILENAME={exe_name}"],
                cwd=bug_dir,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                timeout=30
            )
            if result.returncode == 0:
                return True

        result = subprocess.run(
            [
                "gcc",
                "-fno-optimize-sibling-calls", "-fno-strict-aliasing",
                "-fno-asm", "-std=c99",
                "-Wno-error=implicit-function-declaration",
                "-O0",
                source_name, "-o", exe_name, "-lm"
            ],
            cwd=bug_dir,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            timeout=30
        )
        return result.returncode == 0

    def _run_one_test(self, exe_path, input_file, expected_output_file, timeout=10):
        """
        Chạy exe với input, so sánh stdout với expected output.
        So sánh ignore trailing whitespace mỗi dòng (tương đương diff --ignore-trailing-space).

        Dùng stdin=PIPE + communicate(input=data) để Python quản lý cả stdin/stdout
        qua pipe — timeout mới hoạt động đúng trên mọi nền tảng (kể cả macOS Python 3.9).
        Dùng start_new_session=True + os.killpg(SIGKILL) để kill toàn process group.
        """
        try:
            with open(input_file, "r") as f:
                input_data = f.read()
            with open(expected_output_file, "r") as f:
                expected = f.read()
        except Exception:
            return False

        try:
            proc = subprocess.Popen(
                [exe_path],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                start_new_session=True,  # proc.pid == pgid khi dùng start_new_session
            )
            try:
                stdout, _ = proc.communicate(input=input_data, timeout=timeout)
            except subprocess.TimeoutExpired:
                # SIGKILL toàn bộ process group
                try:
                    os.killpg(proc.pid, signal.SIGKILL)
                except (ProcessLookupError, PermissionError):
                    proc.kill()
                # Drain pipes với timeout ngắn để tránh block vô hạn
                try:
                    proc.communicate(timeout=2)
                except subprocess.TimeoutExpired:
                    pass
                return False
        except Exception:
            try:
                proc.kill()
                proc.wait()
            except Exception:
                pass
            return False

        return _compare_output(stdout or "", expected)


class Defects4CAdapter(SandboxAdapter):
    """Adapter validate patch Defects4C qua Docker/local service đã warmup."""

    def __init__(self, bug_id, data_folder: Optional[str] = None):
        super().__init__(bug_id)
        self.data_folder = data_folder

    def get_source_path(self):
        return get_defects4c_source_path(self.bug_id, data_folder=self.data_folder)

    def prepare_compilation_database(
        self, *, source_root: str, source_path: str, src_relpath: Optional[str] = None
    ) -> dict:
        """Build/export the same compilation context used by metadata validation."""
        del source_path, src_relpath
        cached = getattr(self, "_analysis_compilation_context", None)
        cached_database = str((cached or {}).get("database_path") or "")
        if (
            isinstance(cached, dict)
            and cached.get("available")
            and cached_database
            and os.path.isfile(cached_database)
        ):
            return dict(cached)
        raw = get_defects4c_raw_record(self.bug_id, data_folder=self.data_folder)
        bug_meta = (raw or {}).get("raw", raw or {})
        analysis_root = os.path.realpath(source_root)
        build_root = os.path.realpath(str(bug_meta.get("source_repo_dir") or ""))
        container_root = str(bug_meta.get("container_repo_dir") or "")
        database = find_build_compilation_database([analysis_root, build_root])
        diagnostics = []
        if not database:
            database, prepare_diagnostics = self._export_metadata_compilation_database(
                bug_meta=bug_meta,
            )
            diagnostics.extend(prepare_diagnostics)
        if not database:
            context = {
                "version": 1,
                "available": False,
                "database_path": "",
                "provider": "defects4c_metadata_build",
                "diagnostics": diagnostics or ["metadata_build_compilation_database_missing"],
            }
            # A later sandbox build may create the database.  Do not make a
            # transient build/export failure sticky for the adapter lifetime.
            return context
        output = os.path.join(analysis_root, ".apr", "compile_commands.json")
        mappings = [(container_root, build_root)] if container_root and build_root else []
        context = materialize_analysis_database(
            source_database=database,
            output_database=output,
            build_source_root=build_root or analysis_root,
            analysis_source_root=analysis_root,
            path_mappings=mappings,
        )
        context["provider"] = "defects4c_metadata_build"
        context["diagnostics"] = list(dict.fromkeys([
            *diagnostics, *(context.get("diagnostics") or [])
        ]))
        self._analysis_compilation_context = dict(context)
        return context

    def _export_metadata_compilation_database(self, *, bug_meta: dict) -> Tuple[str, list]:
        container = self._select_defects4c_container(bug_meta)
        container_repo = str(bug_meta.get("container_repo_dir") or "")
        compile_cmd = str(bug_meta.get("compile_cmd") or "").strip()
        commit_after = str(bug_meta.get("commit_after") or "")
        commit_before = str(bug_meta.get("commit_before") or "")
        if not container or not container_repo or not compile_cmd:
            return "", ["metadata_compilation_database_build_context_missing"]
        if not self._prepare_generic_workspace(
            container=container,
            container_repo=container_repo,
            commit_after=commit_after,
            commit_before=commit_before,
            src_files=self._phase_a_src_files(bug_meta),
            # Metadata workspaces are persistent and commonly retain a CMake
            # cache configured before CMAKE_EXPORT_COMPILE_COMMANDS was set.
            # Reconfigure from a clean tree so the exported setting is applied
            # before semantic analysis, rather than only during validation.
            clean=True,
        ):
            return "", ["metadata_compilation_database_workspace_prepare_failed"]
        timeout = int(os.getenv("APR_COMPILE_DATABASE_TIMEOUT_SECONDS", "1800"))
        quoted_compile = shlex.quote(compile_cmd)
        database_output = shlex.quote(f"{container_repo.rstrip('/')}/compile_commands.json")
        script = (
            "export CMAKE_EXPORT_COMPILE_COMMANDS=ON; "
            "if command -v bear >/dev/null 2>&1; then "
            f"timeout --kill-after=10s {shlex.quote(str(timeout) + 's')} "
            f"bear --output {database_output} -- bash -lc {quoted_compile}; "
            "else "
            f"timeout --kill-after=10s {shlex.quote(str(timeout) + 's')} "
            f"bash -lc {quoted_compile}; "
            "fi"
        )
        try:
            completed = subprocess.run(
                ["docker", "exec", container, "bash", "-lc", script],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=timeout + 30,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return "", [f"metadata_compilation_database_build_failed:{type(exc).__name__}"]
        diagnostics = []
        if completed.returncode != 0:
            diagnostics.append(f"metadata_compilation_build_nonzero:{completed.returncode}")
        find_cmd = (
            f"find {shlex.quote(container_repo)} -maxdepth 3 -name compile_commands.json "
            "-type f -print -quit"
        )
        located = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", find_cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        container_database = (located.stdout or "").strip().splitlines()
        if located.returncode != 0 or not container_database:
            return "", [*diagnostics, "metadata_build_did_not_export_compile_commands"]
        host_build_root = os.path.realpath(str(bug_meta.get("source_repo_dir") or ""))
        relative = os.path.relpath(container_database[0], container_repo)
        host_database = os.path.realpath(os.path.join(host_build_root, relative))
        if not os.path.isfile(host_database):
            return "", [*diagnostics, "metadata_compile_commands_not_host_mapped"]
        return host_database, diagnostics

    def validate(self, patched_file_path, src_basename=None, src_relpath=None,
                 exclude_fixed_fail_tests=True):
        self.last_validation_details = {}
        raw = get_defects4c_raw_record(self.bug_id, data_folder=self.data_folder)
        if not raw:
            return self._validation_error_result("metadata_not_found")

        bug_meta = raw.get("raw", raw)
        if not src_relpath and not src_basename:
            return self._validation_error_result("missing_src_target")

        project = bug_meta.get("project") or parse_defects4c_bug_id(self.bug_id)[0]
        sha = bug_meta.get("commit_after") or parse_defects4c_bug_id(self.bug_id)[1]
        commit_before = bug_meta.get("commit_before")
        if not commit_before:
            return self._validation_error_result("missing_commit_before")
        if not sha:
            return self._validation_error_result("missing_commit_after")

        test_ids = self._collect_defects4c_test_ids(
            project,
            sha,
            bug_meta,
            exclude_fixed_fail_tests=exclude_fixed_fail_tests,
        )
        try:
            with open(patched_file_path, "rb") as f:
                content = f.read()
        except Exception:
            return self._validation_error_result("patch_read_error")

        # Giữ artifact patch như luồng cũ để tiện trace/debug.
        md5 = hashlib.md5(content).hexdigest()
        host_patch_dir = os.path.join(DEFECTS4C_PATCHES_DIR, project, "unified_debugging")
        os.makedirs(host_patch_dir, exist_ok=True)
        patch_label = (src_relpath or src_basename or "unknown").replace("/", "__")
        host_patch_path = os.path.join(host_patch_dir, f"{md5}@{sha}___{patch_label}")
        with open(host_patch_path, "wb") as f:
            f.write(content)

        return self._validate_metadata_patch(
            patched_file_path=patched_file_path,
            src_basename=src_basename,
            src_relpath=src_relpath,
            bug_meta=bug_meta,
            project=project,
            commit_after=sha,
            commit_before=commit_before,
            test_ids=test_ids,
            exclude_fixed_fail_tests=exclude_fixed_fail_tests,
        )

    def _validate_metadata_patch(
        self,
        patched_file_path: str,
        src_basename: str,
        src_relpath: Optional[str],
        bug_meta: dict,
        project: str,
        commit_after: str,
        commit_before: str,
        test_ids: list,
        exclude_fixed_fail_tests: bool = True,
    ):
        host_repo = bug_meta.get("source_repo_dir") or ""
        container_repo = bug_meta.get("container_repo_dir") or ""
        if not host_repo or not os.path.isdir(host_repo):
            return self._validation_error_result("repo_not_found")
        if not container_repo:
            return self._validation_error_result("container_repo_not_found")

        container = self._select_defects4c_container(bug_meta)
        if not container:
            return self._validation_error_result("container_not_running")

        src_files = self._phase_a_src_files(bug_meta)
        if not self._prepare_generic_workspace(
            container=container,
            container_repo=container_repo,
            commit_after=commit_after,
            commit_before=commit_before,
            src_files=src_files,
            clean=True,
        ):
            return self._validation_error_result("phase_a_prepare_failed")

        build_compat_patches = []
        try:
            build_compat_patches = self._apply_known_build_compatibility_patches(
                container=container,
                container_repo=container_repo,
                bug_meta=bug_meta,
            )
            if build_compat_patches is None:
                return self._validation_error_result("build_compat_patch_failed")

            target_relpath = self._resolve_source_relpath(
                bug_meta=bug_meta,
                src_basename=src_basename,
                src_relpath=src_relpath,
                src_files=src_files,
            )
            if not target_relpath:
                return self._validation_error_result(f"source_not_found:{src_relpath or src_basename}")

            if not self._apply_generic_patch(container, patched_file_path, container_repo, target_relpath):
                return self._validation_error_result(f"patch_copy_failed:{target_relpath}")

            suite_ok, full_passed, full_failed, validation_error = self._run_metadata_test_suite(
                container=container,
                container_repo=container_repo,
                bug_meta=bug_meta,
                test_ids=test_ids,
            )
        finally:
            self._reset_generic_workspace(container, container_repo)

        if validation_error:
            self.last_validation_details = {
                "validation_error": validation_error,
                "full_post_passed_tests": [],
                "full_post_failed_tests": [],
                "phase_a_suite_ok": False,
                "phase_a_base_commit": commit_after,
                "phase_a_buggy_overlay_commit": commit_before,
                "phase_a_buggy_overlay_files": list(src_files),
                "build_compat_patches": list(build_compat_patches),
                "validation_log_tail": getattr(self, "_last_validation_log_tail", ""),
            }
            return False, [], []

        if (not suite_ok) and (not full_failed) and (not full_passed):
            self.last_validation_details = {
                "validation_error": "metadata_suite_failed",
                "full_post_passed_tests": [],
                "full_post_failed_tests": [],
                "phase_a_suite_ok": False,
                "phase_a_base_commit": commit_after,
                "phase_a_buggy_overlay_commit": commit_before,
                "phase_a_buggy_overlay_files": list(src_files),
                "build_compat_patches": list(build_compat_patches),
                "validation_log_tail": getattr(self, "_last_validation_log_tail", ""),
            }
            return False, [], []

        full_failed_set = set(full_failed)
        full_passed = full_passed or [t for t in test_ids if t not in full_failed_set]
        fixed_fail_tests = self._fixed_fail_excluded_tests(bug_meta)
        fixed_fail_excluded = fixed_fail_tests if exclude_fixed_fail_tests else set()
        comparison_failed = [t for t in full_failed if t not in fixed_fail_excluded]
        comparison_passed = [t for t in full_passed if t not in fixed_fail_excluded]

        self.last_validation_details = {
            "validation_error": "",
            "full_post_passed_tests": list(full_passed),
            "full_post_failed_tests": list(full_failed),
            "fixed_fail_excluded_tests": sorted(fixed_fail_excluded),
            "exclude_fixed_fail_tests_from_run": exclude_fixed_fail_tests,
            "validation_test_count": len(test_ids),
            "phase_a_suite_ok": suite_ok,
            "phase_a_base_commit": commit_after,
            "phase_a_buggy_overlay_commit": commit_before,
            "phase_a_buggy_overlay_files": list(src_files),
            "build_compat_patches": list(build_compat_patches),
            "validation_log_tail": getattr(self, "_last_validation_log_tail", ""),
        }
        print(
            f"    [Defects4C:{bug_meta.get('data_folder', 'metadata')}] full_scope_tests={len(test_ids)} "
            f"full_failed_total={len(full_failed)} comparison_failed_total={len(comparison_failed)}"
        )
        if not comparison_failed:
            return True, list(comparison_passed), []
        return False, list(comparison_passed), list(comparison_failed)

    def _validation_error_result(self, reason: str):
        self.last_validation_details = {
            "validation_error": reason,
            "full_post_passed_tests": [],
            "full_post_failed_tests": [],
        }
        return False, [], []

    def _fixed_fail_excluded_tests(self, bug_meta: dict) -> set:
        tests = bug_meta.get("tests", []) if isinstance(bug_meta, dict) else []
        excluded = set()
        for test in tests:
            if not isinstance(test, dict):
                continue
            tid = str(test.get("test_id") or "").strip()
            if not tid:
                continue
            outcome = str(test.get("outcome") or "").upper()
            outcome_fixed = str(test.get("outcome_fixed") or "").upper()
            if outcome in ("FAIL", "FAILED") and outcome_fixed in ("FAIL", "FAILED"):
                excluded.add(tid)
        return excluded

    def _resolve_source_relpath(
        self,
        bug_meta: dict,
        src_basename: Optional[str],
        src_relpath: Optional[str],
        src_files: Optional[list] = None,
    ) -> Optional[str]:
        buggy_tree_dir = bug_meta.get("buggy_tree_dir") or ""
        if src_relpath:
            rel = src_relpath.strip().replace("\\", "/")
            if rel and not rel.startswith("/") and ".." not in rel.split("/"):
                buggy_path = os.path.join(buggy_tree_dir, rel) if buggy_tree_dir else ""
                if not buggy_tree_dir or os.path.isfile(buggy_path):
                    return rel
            return None

        if not src_basename:
            return None
        for rel in src_files or []:
            if os.path.basename(rel) != src_basename:
                continue
            exact = os.path.join(buggy_tree_dir, rel) if buggy_tree_dir else ""
            if os.path.isfile(exact):
                return rel

        return None

    def _select_defects4c_container(self, bug_meta: Optional[dict] = None) -> str:
        bug_meta = bug_meta or {}
        env_c = (os.getenv("DEFECTS4C_CONTAINER") or "").strip()
        folder = str(bug_meta.get("data_folder") or bug_meta.get("metadata_slug") or "").strip()
        project = str(bug_meta.get("project") or "").strip()
        project_tail = project.split("___")[-1].lower() if project else ""
        candidates = []
        if env_c:
            candidates.append(env_c)
        if folder:
            candidates.append(f"my_defects4c_{folder.lower()}")
        if project_tail and project_tail != folder.lower():
            candidates.append(f"my_defects4c_{project_tail}")
        candidates.append("my_defects4c")
        for name in dict.fromkeys(candidates):
            if shutil.which("docker") and self._docker_container_running(name):
                return name
        return ""

    def _phase_a_src_files(self, bug_meta: dict) -> list:
        values = bug_meta.get("src_files")
        if not isinstance(values, list) or not values:
            files = bug_meta.get("files", {})
            if isinstance(files, dict):
                values = files.get("src", [])
        if not isinstance(values, list) or not values:
            rel = bug_meta.get("source_relpath")
            values = [rel] if rel else []

        out = []
        for value in values:
            if not isinstance(value, str):
                continue
            cleaned = value.strip().replace("\\", "/")
            if cleaned and not cleaned.startswith("/") and ".." not in cleaned.split("/"):
                out.append(cleaned)
        return list(dict.fromkeys(out))

    def _prepare_generic_workspace(
        self,
        container: str,
        container_repo: str,
        commit_after: str,
        commit_before: str,
        src_files: list,
        clean: bool,
    ) -> bool:
        clean_cmd = "git -C \"$repo\" clean -ffdx && " if clean else ""
        overlay_cmd = ""
        if src_files:
            src_args = " ".join(shlex.quote(path) for path in src_files)
            overlay_cmd = f" && git -C \"$repo\" checkout --force \"$before\" -- {src_args}"
        restore_test_helper_cmd = self._restore_known_test_helpers_cmd()
        cmd = (
            f"repo={shlex.quote(container_repo)}; "
            f"after={shlex.quote(commit_after)}; "
            f"before={shlex.quote(commit_before)}; "
            "if [ ! -d \"$repo/.git\" ]; then exit 2; fi; "
            "git -C \"$repo\" reset --hard && "
            f"{clean_cmd}"
            "git -C \"$repo\" checkout -f \"$after\""
            f"{overlay_cmd} && "
            f"{restore_test_helper_cmd}"
        )
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return result.returncode == 0

    def _apply_known_build_compatibility_patches(
        self,
        container: str,
        container_repo: str,
        bug_meta: dict,
    ) -> Optional[list]:
        """Apply narrow environment fixes needed to build old projects on newer toolchains."""
        folder = str(bug_meta.get("data_folder") or bug_meta.get("metadata_slug") or "").lower()
        project = str(bug_meta.get("project") or "").lower()
        applied = []

        if self._is_libyang_project(bug_meta):
            result = subprocess.run(
                ["docker", "exec", "-i", container, "python3", "-", container_repo],
                input=LIBYANG_CMOCKA_FILTER_PATCH_SCRIPT,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
            if result.returncode != 0:
                self._last_validation_log_tail = (result.stderr or result.stdout or "")[-4000:]
                return None
            applied.extend(
                line.strip() for line in (result.stdout or "").splitlines() if line.strip()
            )

        if folder != "php" and "php-src" not in project:
            return applied

        cmd = (
            f"repo={shlex.quote(container_repo)}; "
            "if [ \"$(uname -m)\" != \"aarch64\" ]; then exit 0; fi; "
            "file=\"$repo/Zend/zend_multiply.h\"; "
            "if [ ! -f \"$file\" ]; then exit 0; fi; "
            "if grep -q '\"=X\"(__tmpvar), \"=X\"(usedval)' \"$file\" "
            "&& grep -q '\"X\"(a), \"X\"(b)' \"$file\"; then "
            "sed -i 's/\"=X\"(__tmpvar), \"=X\"(usedval)/\"=r\"(__tmpvar), \"=r\"(usedval)/; "
            "s/\"X\"(a), \"X\"(b)/\"r\"(a), \"r\"(b)/' \"$file\"; "
            "echo php_aarch64_zend_multiply_register_constraints; "
            "fi"
        )
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if result.returncode != 0:
            self._last_validation_log_tail = (result.stderr or result.stdout or "")[-4000:]
            return None
        applied.extend(line.strip() for line in (result.stdout or "").splitlines() if line.strip())
        return applied

    @staticmethod
    def _is_libyang_project(bug_meta: dict) -> bool:
        folder = str(
            (bug_meta or {}).get("data_folder")
            or (bug_meta or {}).get("metadata_slug")
            or ""
        ).lower()
        project = str((bug_meta or {}).get("project") or "").lower()
        return folder == "libyang" or "libyang" in project

    def _restore_known_test_helpers_cmd(self) -> str:
        tcpdump_runner = shlex.quote(TCPDUMP_RUN_ONE_TEST_SH)
        return (
            "if [ -f \"$repo/tests/TESTLIST\" ] && [ -x \"$repo/tests/TESTonce\" ] "
            "&& [ ! -f \"$repo/run_one_test.sh\" ]; then "
            f"printf %s {tcpdump_runner} > \"$repo/run_one_test.sh\" && "
            "chmod +x \"$repo/run_one_test.sh\"; "
            "fi"
        )

    def _reset_generic_workspace(self, container: str, container_repo: str) -> bool:
        cmd = (
            f"repo={shlex.quote(container_repo)}; "
            "if [ -d \"$repo/.git\" ]; then "
            "git -C \"$repo\" reset --hard >/dev/null 2>&1; "
            "fi"
        )
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return result.returncode == 0

    def _apply_generic_patch(
        self,
        container: str,
        patched_file_path: str,
        container_repo: str,
        relpath: str,
    ) -> bool:
        rel = (relpath or "").strip().replace("\\", "/")
        if not rel or rel.startswith("/") or ".." in rel.split("/"):
            return False

        container_target = f"{container_repo.rstrip('/')}/{rel}"
        tmp_in_container = f"/tmp/apr_patch_{int(time.time() * 1000)}_{os.getpid()}.c"
        cp_in = subprocess.run(
            ["docker", "cp", patched_file_path, f"{container}:{tmp_in_container}"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if cp_in.returncode != 0:
            return False
        install_cmd = (
            f"dst={shlex.quote(container_target)}; "
            f"tmp={shlex.quote(tmp_in_container)}; "
            "mkdir -p \"$(dirname \"$dst\")\" && cp \"$tmp\" \"$dst\" && rm -f \"$tmp\""
        )
        cp_out = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", install_cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return cp_out.returncode == 0

    def _run_metadata_test_suite(
        self,
        container: str,
        container_repo: str,
        bug_meta: dict,
        test_ids: list,
    ) -> Tuple[bool, list, list, str]:
        compile_cmd = (bug_meta.get("compile_cmd") or "").strip()
        template = (bug_meta.get("test_cmd_template") or "").strip()
        if not compile_cmd or not template or not test_ids:
            return False, [], [], "metadata_suite_config_missing"
        compile_timeout = int(os.getenv("APR_VALIDATE_COMPILE_TIMEOUT_SECONDS", "1800"))
        test_timeout = int(os.getenv("APR_VALIDATE_TEST_TIMEOUT_SECONDS", "180"))

        helper_path = self._extract_metadata_helper_path(template)
        if helper_path:
            self._ensure_metadata_test_helper(
                container=container,
                container_repo=container_repo,
                bug_meta=bug_meta,
                helper_path=helper_path,
            )
        lines = [
            "set +e",
            f"cd {shlex.quote(container_repo)} || exit 2",
            "export CMAKE_EXPORT_COMPILE_COMMANDS=ON",
        ]
        if helper_path:
            lines.extend([
                f"if [ ! -f {shlex.quote(helper_path)} ]; then",
                f"  echo __UD_TEST_HELPER_MISSING__ {shlex.quote(helper_path)}",
                "  exit 98",
                "fi",
            ])
        lines.extend([
            "export BUILD_META_TEST_TIMEOUT="
            + shlex.quote(str(test_timeout)),
            "export BUILD_META_COMPILE_TIMEOUT="
            + shlex.quote(str(compile_timeout)),
            f"(timeout --kill-after=10s {shlex.quote(str(compile_timeout) + 's')} "
            f"bash -lc {shlex.quote(compile_cmd)}) >/tmp/udbg_compile.log 2>&1",
            "compile_rc=$?",
            "if [ $compile_rc -ne 0 ]; then echo __UD_COMPILE_FAIL__; tail -80 /tmp/udbg_compile.log; exit 97; fi",
        ])
        for tid in test_ids:
            test_cmd = template.replace("{test_id}", shlex.quote(tid))
            marker = shlex.quote(tid)
            lines.extend([
                f"(timeout --kill-after=10s {shlex.quote(str(test_timeout) + 's')} "
                f"bash -lc {shlex.quote(test_cmd)}) >/tmp/udbg_test.log 2>&1",
                "rc=$?",
                f"if [ $rc -eq 124 ] || [ $rc -eq 137 ]; then echo __UD_TIMEOUT__ {marker}; tail -40 /tmp/udbg_test.log; exit 96; fi",
                f"if [ $rc -eq 0 ]; then echo __UD_PASS__ {marker}; else echo __UD_FAIL__ {marker}; tail -40 /tmp/udbg_test.log; fi",
            ])
        script = "\n".join(lines)
        result = subprocess.run(
            ["docker", "exec", "-i", container, "bash", "-s"],
            input=script,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60 * 40,
        )
        self._last_validation_log_tail = "\n".join(
            (result.stdout or result.stderr or "").splitlines()[-120:]
        )
        passed, failed = [], []
        for line in (result.stdout or "").splitlines():
            if line.startswith("__UD_PASS__ "):
                passed.append(line.split(" ", 1)[1].strip())
            elif line.startswith("__UD_FAIL__ "):
                failed.append(line.split(" ", 1)[1].strip())
            elif line.startswith("__UD_TIMEOUT__ "):
                timed_out = line.split(" ", 1)[1].strip()
                return False, passed, failed, f"test_timeout:{timed_out}"
            elif line.startswith("__UD_TEST_HELPER_MISSING__ "):
                missing = line.split(" ", 1)[1].strip()
                return False, [], [], f"test_helper_missing:{missing}"
        if result.returncode == 96:
            return False, passed, failed, "test_timeout"
        if result.returncode == 97:
            return False, [], [], "compile_failed"
        if result.returncode == 98:
            return False, [], [], "test_helper_missing"
        completed = len(passed) + len(failed)
        if completed < len(test_ids):
            return False, passed, failed, f"metadata_suite_incomplete:{completed}/{len(test_ids)}"
        if result.returncode != 0 and not failed and not passed:
            return False, [], [], "metadata_suite_failed"
        return not failed, passed, failed, ""

    def _extract_metadata_helper_path(self, template: str) -> Optional[str]:
        try:
            parts = shlex.split(template)
        except ValueError:
            return None
        for part in parts:
            if part.endswith(".sh") and "{test_id}" not in part:
                return part
        return None

    def _ensure_metadata_test_helper(
        self,
        container: str,
        container_repo: str,
        bug_meta: dict,
        helper_path: str,
    ) -> bool:
        helper = (helper_path or "").strip()
        repo = (container_repo or "").rstrip("/")
        if not helper or not repo:
            return False
        if os.path.basename(helper) != "run_one_test.sh":
            return False
        if not helper.startswith(repo + "/"):
            return False

        script = self._metadata_run_one_test_script(bug_meta)
        if not script:
            return False
        cmd = (
            f"helper={shlex.quote(helper)}; "
            "mkdir -p \"$(dirname \"$helper\")\" && "
            f"printf %s {shlex.quote(script)} > \"$helper\" && "
            "chmod +x \"$helper\""
        )
        result = subprocess.run(
            ["docker", "exec", container, "bash", "-lc", cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return result.returncode == 0

    def _metadata_run_one_test_script(self, bug_meta: dict) -> str:
        project = str((bug_meta or {}).get("project") or "").strip()
        if not project:
            return ""

        if project == "php___php-src":
            return self._php_run_one_test_script()
        if project == "fmtlib___fmt":
            return self._fmt_run_one_test_script()
        if project == "CESNET___libyang":
            return self._libyang_run_one_test_script()

        project_dir = os.path.join(DEFECTS4C_TPL_DIR, "projects_v1", project)
        if not os.path.isdir(project_dir):
            project_dir = os.path.join(DEFECTS4C_TPL_DIR, "projects", project)
        if not os.path.isdir(project_dir):
            return ""

        for path in sorted(glob.glob(os.path.join(project_dir, "build_meta*.py"))):
            script, build_dir = self._read_run_one_test_from_build_meta(path)
            if script:
                return script.replace("__BUILD_DIR_NAME__", build_dir or "build_meta")
        return ""

    def _libyang_run_one_test_script(self) -> str:
        return textwrap.dedent(r"""
            #!/usr/bin/env bash
            # Auto-generated by Unified-Debugging validation.
            set -uo pipefail
            HERE=$(cd "$(dirname "$0")" && pwd)
            TEST_ID="${1:?Usage: $0 <test_id>}"
            BUILD_DIR="$HERE/build_meta_libyang"
            TEST_TIMEOUT="${BUILD_META_TEST_TIMEOUT:-180}"
            if [[ "$TEST_ID" == *"::"* ]]; then
              CTEST_NAME="${TEST_ID%%::*}"
              CASE_NAME="${TEST_ID#*::}"
              OUTPUT=$(python3 - "$BUILD_DIR" "$CTEST_NAME" "$CASE_NAME" "$TEST_TIMEOUT" 2>&1 <<'PY'
            import json
            import os
            import subprocess
            import sys

            build_dir, ctest_name, case_name, timeout_text = sys.argv[1:]
            try:
                timeout_seconds = max(1, int(timeout_text))
                metadata = subprocess.run(
                    ["ctest", "--test-dir", build_dir, "--show-only=json-v1"],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    check=True,
                )
                payload = json.loads(metadata.stdout)
            except (OSError, ValueError, subprocess.CalledProcessError) as exc:
                print("[run_one_test] unable to read CTest metadata: {}".format(exc), file=sys.stderr)
                raise SystemExit(2)

            tests = [item for item in payload.get("tests", []) if item.get("name") == ctest_name]
            if len(tests) != 1:
                print(
                    "[run_one_test] expected exactly one CTest target named {!r}, found {}".format(
                        ctest_name, len(tests)
                    ),
                    file=sys.stderr,
                )
                raise SystemExit(2)

            test = tests[0]
            command = [str(value) for value in test.get("command") or []]
            if not command:
                print("[run_one_test] CTest target has no command: {}".format(ctest_name), file=sys.stderr)
                raise SystemExit(2)
            properties = {
                str(item.get("name") or ""): item.get("value")
                for item in test.get("properties") or []
                if isinstance(item, dict) and item.get("name")
            }

            original_env = os.environ.copy()
            test_env = original_env.copy()
            for assignment in properties.get("ENVIRONMENT") or []:
                key, separator, value = str(assignment).partition("=")
                if separator and key:
                    test_env[key] = value

            for modification in properties.get("ENVIRONMENT_MODIFICATION") or []:
                key, separator, operation_value = str(modification).partition("=")
                operation, colon, value = operation_value.partition(":")
                if not separator or not colon or not key:
                    print("[run_one_test] invalid CTest environment modification: {}".format(modification), file=sys.stderr)
                    raise SystemExit(2)
                current = test_env.get(key, "")
                if operation == "reset":
                    if key in original_env:
                        test_env[key] = original_env[key]
                    else:
                        test_env.pop(key, None)
                elif operation == "set":
                    test_env[key] = value
                elif operation == "unset":
                    test_env.pop(key, None)
                elif operation == "string_append":
                    test_env[key] = current + value
                elif operation == "string_prepend":
                    test_env[key] = value + current
                elif operation == "path_list_append":
                    test_env[key] = current + (os.pathsep if current and value else "") + value
                elif operation == "path_list_prepend":
                    test_env[key] = value + (os.pathsep if current and value else "") + current
                elif operation == "cmake_list_append":
                    test_env[key] = current + (";" if current and value else "") + value
                elif operation == "cmake_list_prepend":
                    test_env[key] = value + (";" if current and value else "") + current
                else:
                    print("[run_one_test] unsupported CTest environment modification: {}".format(operation), file=sys.stderr)
                    raise SystemExit(2)

            test_env["BUILD_META_CMOCKA_TEST_FILTER"] = case_name
            working_directory = str(properties.get("WORKING_DIRECTORY") or build_dir)
            try:
                completed = subprocess.run(
                    command,
                    cwd=working_directory,
                    env=test_env,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    timeout=timeout_seconds,
                )
            except subprocess.TimeoutExpired as exc:
                if exc.stdout:
                    print(exc.stdout, end="" if str(exc.stdout).endswith("\n") else "\n")
                print("[run_one_test] CMocka test timed out: {}".format(ctest_name), file=sys.stderr)
                raise SystemExit(124)
            except OSError as exc:
                print("[run_one_test] unable to execute CTest command: {}".format(exc), file=sys.stderr)
                raise SystemExit(2)

            if completed.stdout:
                print(completed.stdout, end="" if completed.stdout.endswith("\n") else "\n")
            raise SystemExit(completed.returncode if completed.returncode >= 0 else 128 - completed.returncode)
            PY
              )
            else
              OUTPUT=$(ctest --test-dir "$BUILD_DIR" -R "^${TEST_ID}$" -V --timeout "$TEST_TIMEOUT" 2>&1)
            fi
            STATUS=$?
            echo "$OUTPUT"
            if [[ $STATUS -ne 0 ]] || echo "$OUTPUT" | grep -Eq '\*\*\*Failed|\[  FAILED  \]|FAILED TEST\(S\)'; then
              exit 1
            fi
            if [[ "$TEST_ID" == *"::"* ]]; then
              SELECTED_CASES=$(echo "$OUTPUT" | sed -nE 's/^\[[[:space:]]*RUN[[:space:]]*\][[:space:]]+//p')
              if [[ -z "$SELECTED_CASES" ]] || echo "$SELECTED_CASES" | grep -Fvxq "$CASE_NAME"; then
                echo "[run_one_test] CMocka filter selected no case or a different case: $TEST_ID" >&2
                exit 1
              fi
            fi
            exit 0
        """).lstrip()

    def _fmt_run_one_test_script(self) -> str:
        return textwrap.dedent(r"""
            #!/usr/bin/env bash
            # Auto-generated by Unified-Debugging validation.
            set -uo pipefail
            HERE=$(cd "$(dirname "$0")" && pwd)
            TEST_ID="${1:?Usage: $0 <test_id>}"
            BUILD_DIR="$HERE/build_meta_fmt"
            TEST_WORK_DIR="$BUILD_DIR/test"
            TEST_TIMEOUT="${BUILD_META_TEST_TIMEOUT:-180}"
            if [[ "$TEST_ID" == *"::"* ]]; then
              CTEST_NAME="${TEST_ID%%::*}"
              GTEST_FILTER="${TEST_ID#*::}"
              OUTPUT=$(cd "$TEST_WORK_DIR" && timeout --kill-after=10s "${TEST_TIMEOUT}s" "$BUILD_DIR/bin/$CTEST_NAME" --gtest_filter="$GTEST_FILTER" --gtest_color=no 2>&1)
            else
              OUTPUT=$(ctest --test-dir "$BUILD_DIR" -R "^${TEST_ID}$" -V --timeout "$TEST_TIMEOUT" 2>&1)
            fi
            STATUS=$?
            echo "$OUTPUT"
            if [[ $STATUS -ne 0 ]] || echo "$OUTPUT" | grep -Eq '\*\*\*Failed|\[  FAILED  \]'; then
              exit 1
            fi
            if [[ "$TEST_ID" == *"::"* ]] && echo "$OUTPUT" | grep -q 'Running 0 tests'; then
              exit 1
            fi
            exit 0
        """).lstrip()

    def _read_run_one_test_from_build_meta(self, path: str) -> Tuple[str, str]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                tree = ast.parse(f.read(), filename=path)
        except Exception:
            return "", ""

        script = ""
        build_dir = ""
        for node in tree.body:
            if not isinstance(node, ast.Assign):
                continue
            names = [target.id for target in node.targets if isinstance(target, ast.Name)]
            if "BUILD_DIR_NAME" in names:
                value = self._literal_string_from_ast(node.value)
                if value:
                    build_dir = value
            if "RUN_ONE_TEST_SH" in names:
                value = self._literal_string_from_ast(node.value)
                if value:
                    script = textwrap.dedent(value).lstrip()
        return script, build_dir

    def _literal_string_from_ast(self, node) -> str:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        if isinstance(node, ast.Call):
            # Handles textwrap.dedent("...").lstrip() and textwrap.dedent("...").
            if isinstance(node.func, ast.Attribute) and node.func.attr == "lstrip":
                return self._literal_string_from_ast(node.func.value)
            if node.args:
                return self._literal_string_from_ast(node.args[0])
        return ""

    def _php_run_one_test_script(self) -> str:
        return textwrap.dedent(r"""
            #!/usr/bin/env bash
            # Auto-generated by Unified-Debugging validation.
            set -euo pipefail
            ROOT=$(cd "$(dirname "$0")" && pwd)
            export NO_INTERACTION=1
            export TEST_PHP_EXECUTABLE="$ROOT/sapi/cli/php"
            TEST_ID="${1:?usage: run_one_test.sh <test_id>}"
            TEST_REL="$TEST_ID"
            [[ "$TEST_REL" == *.phpt ]] || TEST_REL="${TEST_REL}.phpt"
            if [[ ! -f "$ROOT/$TEST_REL" ]]; then
              echo "unknown test_id: $TEST_ID" >&2
              exit 2
            fi
            cd "$ROOT"
            set +e
            output=$(sapi/cli/php run-tests.php -q -p sapi/cli/php -g FAIL,XFAIL,BORK,WARN,LEAK,SKIP "$TEST_REL" 2>&1)
            rc=$?
            set -e
            printf '%s\n' "$output"

            if printf '%s\n' "$output" | grep -Eq '^(FAIL|BORK|WARN|LEAK)[[:space:]]'; then
              exit 1
            fi
            if printf '%s\n' "$output" | grep -Eq 'Tests failed[[:space:]]*:[[:space:]]*[1-9]'; then
              exit 1
            fi
            if printf '%s\n' "$output" | grep -Eq 'Tests borked[[:space:]]*:[[:space:]]*[1-9]'; then
              exit 1
            fi
            if printf '%s\n' "$output" | grep -Eq 'Tests warned[[:space:]]*:[[:space:]]*[1-9]'; then
              exit 1
            fi
            exit "$rc"
        """).lstrip()

    def _collect_defects4c_test_ids(
        self,
        project: str,
        sha: str,
        bug_meta: Optional[dict] = None,
        exclude_fixed_fail_tests: bool = True,
    ) -> list:
        metadata_ids = self._metadata_test_ids_from_bug_meta(
            bug_meta or {},
            exclude_fixed_fail_tests=exclude_fixed_fail_tests,
        )
        if metadata_ids:
            return metadata_ids

        host_repo = (bug_meta or {}).get("source_repo_dir") or os.path.join(
            DEFECTS4C_OUT_DIR,
            project,
            f"git_repo_dir_{sha}",
        )
        host_testlist = os.path.join(
            host_repo,
            "tests",
            "TESTLIST",
        )
        if not os.path.isfile(host_testlist):
            return []
        ids = []
        try:
            with open(host_testlist, "r", errors="ignore") as f:
                for line in f:
                    s = line.strip()
                    if not s or s.startswith("#"):
                        continue
                    parts = s.split()
                    if parts:
                        ids.append(parts[0])
        except Exception:
            return []
        return ids

    def _metadata_test_ids_from_bug_meta(
        self,
        bug_meta: dict,
        exclude_fixed_fail_tests: bool = True,
    ) -> list:
        tests = bug_meta.get("tests", []) if isinstance(bug_meta, dict) else []
        out = []
        for test in tests:
            if not isinstance(test, dict):
                continue
            if is_zero_test_noop_pass_test(test):
                continue
            if exclude_fixed_fail_tests:
                outcome = str(test.get("outcome") or "").upper()
                outcome_fixed = str(test.get("outcome_fixed") or "").upper()
                if outcome in ("FAIL", "FAILED") and outcome_fixed in ("FAIL", "FAILED"):
                    continue
            tid = str(test.get("test_id", "")).strip()
            if tid:
                out.append(tid)
        return self._unique_test_ids(out)

    @staticmethod
    def _unique_test_ids(values) -> list:
        seen = set()
        out = []
        for value in values:
            if value in seen:
                continue
            seen.add(value)
            out.append(value)
        return out

    def _docker_container_running(self, container):
        try:
            result = subprocess.run(
                ["docker", "inspect", "-f", "{{.State.Running}}", container],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=10,
            )
        except (subprocess.TimeoutExpired, OSError):
            return False
        return result.returncode == 0 and result.stdout.decode(errors="replace").strip() == "true"


def _compare_output(actual: str, expected: str) -> bool:
    """
    So sánh output giống diff --brief --ignore-trailing-space:
    bỏ qua trailing whitespace mỗi dòng, bỏ qua trailing newlines cuối file.
    """
    actual_lines = [line.rstrip() for line in actual.splitlines()]
    expected_lines = [line.rstrip() for line in expected.splitlines()]

    while actual_lines and actual_lines[-1] == "":
        actual_lines.pop()
    while expected_lines and expected_lines[-1] == "":
        expected_lines.pop()

    return actual_lines == expected_lines


def defects4c_docker_ready(dataset_name: str = "defects4c") -> Tuple[bool, str]:
    """
    Kiểm tra APR/validate Defects4C có thể chạy không (Docker + container đang Running).

    Returns:
        (True, container_name) nếu tìm được container phù hợp.
        (False, message) nếu thiếu Docker hoặc không có container nào đang chạy.
    """
    if not shutil.which("docker"):
        return False, "Docker không có trong PATH — validate patch Defects4C cần Docker."

    candidates = []
    env_c = (os.getenv("DEFECTS4C_CONTAINER") or "").strip()
    if env_c:
        candidates.append(env_c)
    ds = (dataset_name or "").strip().lower()
    if ds.startswith("defects4c-"):
        ds = ds[len("defects4c-"):]
    ordered = []
    if ds and ds != "defects4c":
        ordered.append(f"my_defects4c_{ds}")
    ordered.append("my_defects4c")
    for name in ordered:
        if name not in candidates:
            candidates.append(name)

    for name in candidates:
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Running}}", name],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
        if result.returncode == 0 and result.stdout.decode().strip() == "true":
            return True, name

    tried = ", ".join(candidates)
    hint = env_c or (f"my_defects4c_{ds}" if ds and ds != "defects4c" else "my_defects4c")
    return (
        False,
        f"Không có container Defects4C đang chạy (đã thử: {tried}). "
        f"Khởi container rồi chạy lại, hoặc đặt DEFECTS4C_CONTAINER và docker start <tên>. "
        f"Ví dụ: docker start {hint}",
    )


def get_sandbox_adapter(dataset_name, bug_id):
    """Factory để cấp phát Adapter tùy theo dataset_name truyền vào"""
    ds_lc = dataset_name.strip().lower()
    if ds_lc == "codeflaws":
        return CodeflawsAdapter(bug_id)

    # Any non-Codeflaws dataset handled here is expected to be a Defects4C
    # data folder under out_tmp_dirs/unified_debugging/<dataset_name>/metadata.
    defects4c_folder = ds_lc
    if defects4c_folder.startswith("defects4c-"):
        defects4c_folder = defects4c_folder[len("defects4c-"):]
    if ds_lc == "defects4c":
        return Defects4CAdapter(bug_id)
    try:
        if get_defects4c_raw_record(bug_id, data_folder=defects4c_folder):
            return Defects4CAdapter(bug_id, data_folder=defects4c_folder)
    except ValueError:
        pass

    raise ValueError(f"Dataset '{dataset_name}' chưa có Adapter tương ứng hỗ trợ!")
