"""Compiler-backed semantic evidence for I/O-first fault localization."""

from __future__ import annotations

import os
import re
from typing import Any, Dict, Iterable, List

from core.apr.agent.correctness_repair.clang_semantic_provider import (
    resolve_target_semantics,
)
from core.apr.agent.correctness_repair.models import stable_id
from core.apr.common import (
    node_text,
    parse_tree,
    source_language_from_path,
    walk_nodes,
)


_CALL_TYPES = {"call_expression"}
_NOISE_TOKENS = {
    "actual", "assert", "below", "body", "description", "dir", "expected",
    "expect", "failure", "failed", "file", "listed", "note", "running",
    "test", "value", "which", "with",
}


def extract_io_semantics(
    *,
    raw: Dict[str, Any],
    test_id: str,
    source_path: str,
    source: str,
    source_start_line: int,
    focused: Dict[str, Any],
    observations: List[Dict[str, Any]],
    producer_sites: List[Dict[str, Any]],
    runtime_evidence: Dict[str, Any],
) -> Dict[str, Any]:
    """Resolve test calls/types with Clang and retain a syntax-only fallback."""
    lexical_text = _semantic_text(
        source=source,
        observations=observations,
        producer_sites=producer_sites,
    )
    lexical_tokens = semantic_tokens(lexical_text)
    compilation_database = str(
        ((runtime_evidence or {}).get("compile") or {}).get(
            "compilation_database"
        )
        or ""
    )
    result = {
        "version": 1,
        "provider": "source_ast",
        "available": False,
        "compilation_database": compilation_database,
        "tokens": lexical_tokens,
        "resolved_calls": [],
        "resolved_types": [],
        "diagnostics": [],
    }
    if not source_path or not source:
        result["diagnostics"].append("semantic_test_source_unavailable")
        return result
    if not compilation_database or not os.path.isfile(compilation_database):
        result["diagnostics"].append(
            "semantic_compilation_database_unavailable"
        )
        return result

    language = source_language_from_path(source_path)
    records = _call_records(
        source_path=source_path,
        source=source,
        source_start_line=source_start_line,
        language=language,
    )
    if not records:
        result["diagnostics"].append("semantic_test_calls_unavailable")
        return result
    source_range = dict(focused.get("test_source_range") or {})
    if not source_range:
        source_range = _source_range_from_records(records)
    target_name = _clang_test_target_name(test_id=test_id, source=source)
    semantic = resolve_target_semantics(
        source_root=str(
            raw.get("buggy_tree_dir") or raw.get("source_repo_dir") or ""
        ),
        target_contract={
            "source_path": source_path,
            "resolved_name": target_name,
            "requested_name": target_name,
            "language": language,
            "source_range": source_range,
        },
        syntax_ir={"records": records},
        compilation_context={
            "database_path": compilation_database,
            "allowed_source_roots": [
                str(raw.get("buggy_tree_dir") or ""),
            ],
        },
    )
    result["provider"] = str(semantic.get("provider") or "clang_ast")
    result["available"] = bool(semantic.get("available"))
    result["diagnostics"].extend(semantic.get("diagnostics") or [])
    resolved_calls = []
    resolved_types = []
    for record in records:
        resolution = (semantic.get("calls") or {}).get(record["id"]) or {}
        if resolution.get("status") != "compiler_resolved":
            continue
        item = {
            "source_call": record.get("display_name"),
            "resolved_name": resolution.get("resolved_name"),
            "signature": resolution.get("signature"),
            "result_type": resolution.get("result_type"),
            "symbol_id": resolution.get("symbol_id"),
            "definition": resolution.get("definition") or {},
        }
        resolved_calls.append(item)
        for value in (
            item.get("resolved_name"),
            item.get("signature"),
            item.get("result_type"),
        ):
            if value:
                resolved_types.append(str(value))
    result["resolved_calls"] = resolved_calls[:80]
    result["resolved_types"] = list(dict.fromkeys(resolved_types))[:80]
    result["tokens"] = semantic_tokens([
        *lexical_text,
        *resolved_types,
    ])
    if not result["available"] and not result["diagnostics"]:
        result["diagnostics"].append("semantic_clang_resolution_unavailable")
    return result


def _clang_test_target_name(*, test_id: str, source: str) -> str:
    """Return the compiler-visible test function generated by the framework."""
    if re.search(
        r"\b(?:TEST|TEST_F|TEST_P|TYPED_TEST|TYPED_TEST_P)\s*\(",
        source,
    ):
        # GoogleTest expands each test macro to a generated class whose
        # compiler-visible body method is always named TestBody. The exact
        # instance is selected by its source byte range, not by textual name.
        return "TestBody"
    return test_id.split("::")[-1].split(".")[-1]


def semantic_tokens(values: str | Iterable[str]) -> List[str]:
    if isinstance(values, str):
        values = [values]
    output = []
    for value in values:
        for identifier in re.findall(
            r"[A-Za-z_][A-Za-z0-9_]{1,}", str(value or "")
        ):
            parts = re.sub(
                r"([a-z0-9])([A-Z])", r"\1_\2", identifier
            ).lower().split("_")
            original = identifier.lower()
            expanded = [
                *parts,
                *(
                    [original]
                    if "_" not in original and len(original) <= 40
                    else []
                ),
            ]
            for token in expanded:
                if (
                    len(token) >= 3
                    and token not in _NOISE_TOKENS
                    and not token.startswith(("expect", "assert", "test"))
                    and not re.fullmatch(r"[0-9a-f]{16,}", token)
                    and token not in output
                ):
                    output.append(token)
    return output[:160]


def _semantic_text(
    *,
    source: str,
    observations: List[Dict[str, Any]],
    producer_sites: List[Dict[str, Any]],
) -> List[str]:
    values = []
    for observation in observations:
        contract = observation.get("observed_output") or {}
        # ``expressions`` is commonly only a generic destination variable
        # (buffer/out/result). Expected/actual text carries the behavioral
        # contract; the transformation itself comes from resolved calls.
        for field in ("actual", "expected"):
            values.extend(str(item) for item in contract.get(field) or [])
        values.extend(
            str(item)
            for item in contract.get("failure_signals") or []
            if "exception" in str(item).lower()
            and not str(item).lstrip().startswith(("/", "["))
        )
    for site in producer_sites:
        if site.get("role") == "asserted_expression":
            # A bare output variable (``buffer``, ``out``, ``result``) names a
            # container, not the transformation that produced the bad value.
            # Compiler-resolved/source-AST calls are the causal semantic clue.
            values.extend(str(item) for item in site.get("calls") or [])
    if not values:
        values.append(source)
    return values


def _call_records(
    *,
    source_path: str,
    source: str,
    source_start_line: int,
    language: str,
) -> List[Dict[str, Any]]:
    tree, source_bytes = parse_tree(source, language)
    if tree is None or source_bytes is None:
        return []
    try:
        full_source = open(
            source_path, "r", encoding="utf-8", errors="replace"
        ).read()
    except OSError:
        return []
    line_offsets = _line_byte_offsets(full_source)
    records = []
    for node in walk_nodes(tree.root_node):
        if node.type not in _CALL_TYPES:
            continue
        function = node.child_by_field_name("function")
        if function is None:
            continue
        absolute_line = max(1, source_start_line) + int(node.start_point[0])
        if absolute_line - 1 >= len(line_offsets):
            continue
        start_byte = (
            line_offsets[absolute_line - 1] + int(node.start_point[1])
        )
        end_line = max(1, source_start_line) + int(node.end_point[0])
        end_byte = (
            line_offsets[end_line - 1] + int(node.end_point[1])
            if end_line - 1 < len(line_offsets)
            else start_byte + int(node.end_byte - node.start_byte)
        )
        display_name = node_text(function, source_bytes).strip()
        record = {
            "kind": "call",
            "display_name": display_name,
            "source_range": {
                "start_byte": start_byte,
                "end_byte": max(start_byte + 1, end_byte),
                "start_line": absolute_line,
                "end_line": end_line,
            },
        }
        record["id"] = stable_id("fl_test_call", record)
        records.append(record)
    return records


def _source_range_from_records(records: List[Dict[str, Any]]) -> Dict[str, int]:
    starts = [
        int((item.get("source_range") or {}).get("start_byte") or 0)
        for item in records
    ]
    ends = [
        int((item.get("source_range") or {}).get("end_byte") or 0)
        for item in records
    ]
    return {
        "start_byte": min(starts or [0]),
        "end_byte": max(ends or [0]),
    }


def _line_byte_offsets(source: str) -> List[int]:
    offsets = [0]
    total = 0
    for line in source.splitlines(keepends=True):
        total += len(line.encode("utf-8"))
        offsets.append(total)
    return offsets
